[build]
  command = "# no build command" # No frontend to build
  functions = "functions" # Correct directory for your serverless functions
  publish = "" # Can remain as a placeholder if unused

[functions]
  node_bundler = "esbuild" # Use esbuild for bundling serverless functions

[[redirects]]
from = "/*"
to = "/functions/:splat"
status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"