[build]
  command = "# no build command" # No frontend to build
  functions = "./functions" # Correct directory for your serverless functions
  publish = "" # Can remain as a placeholder if unused

[functions]
  node_bundler = "esbuild" # Use esbuild for bundling serverless functions

[[redirects]]
  from = "/projects"
  to = "/.netlify/functions/projects"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PATCH, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
